spring:
  application:
    name: message-system-auth

  datasource:
    source:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: SourceConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000
    replica:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13307/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: ReplicaConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      cluster:
        nodes:
          - localhost:6380
          - localhost:6381
          - localhost:6382
          - localhost:6383
          - localhost:6384
          - localhost:6385
      repositories:
        enabled: false
