version: "3.8"

services:
  mysql-source:
    image: mysql:8.0.40
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "13306:3306"
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
      - ./init-scripts-source:/docker-entrypoint-initdb.d
    command:
      - --server-id=1
      - --log-bin=/var/lib/mysql/mysql-bin.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON

  mysql-replica:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "13307:3306"
    volumes:
      - ${MYSQL_REPLICA_VOLUMES}:/var/lib/mysql
      - ./init-scripts-replica:/docker-entrypoint-initdb.d
    depends_on:
      mysql-source:
        condition: service_healthy
    command:
      - --server-id=2
      - --relay-log=/var/lib/mysql/mysql-relay-bin.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --read-only=ON

  mysql-source-message1:
    image: mysql:8.0.40
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "13308:3306"
    volumes:
      - ${MYSQL_MESSAGE1_VOLUMES}:/var/lib/mysql
      - ./init-scripts-source:/docker-entrypoint-initdb.d
    command:
      - --server-id=3
      - --log-bin=/var/lib/mysql/mysql-bin.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON

  mysql-replica-message1:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "13309:3306"
    volumes:
      - ${MYSQL_MESSAGE1_REPLICA_VOLUMES}:/var/lib/mysql
      - ./init-scripts-replica-message1:/docker-entrypoint-initdb.d
    depends_on:
      mysql-source:
        condition: service_healthy
    command:
      - --server-id=4
      - --relay-log=/var/lib/mysql/mysql-relay-bin.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --read-only=ON

  mysql-source-message2:
    image: mysql:8.0.40
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "13310:3306"
    volumes:
      - ${MYSQL_MESSAGE2_VOLUMES}:/var/lib/mysql
      - ./init-scripts-source:/docker-entrypoint-initdb.d
    command:
      - --server-id=5
      - --log-bin=/var/lib/mysql/mysql-bin.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON

  mysql-replica-message2:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "13311:3306"
    volumes:
      - ${MYSQL_MESSAGE2_REPLICA_VOLUMES}:/var/lib/mysql
      - ./init-scripts-replica-message2:/docker-entrypoint-initdb.d
    depends_on:
      mysql-source:
        condition: service_healthy
    command:
      - --server-id=6
      - --relay-log=/var/lib/mysql/mysql-relay-bin.log
      - --enforce-gtid-consistency=ON
      - --gtid-mode=ON
      - --read-only=ON

  redis-node-1:
    image: bitnamilegacy/redis-cluster:7.4.1
    restart: unless-stopped
    ports:
      - "6380:6380"
      - "16380:16380"
    volumes:
      - ${REDIS_1_VOLUMES}:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_PORT_NUMBER=6380'
      - 'REDIS_NODES=${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6380'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16380'

  redis-node-2:
    image: bitnamilegacy/redis-cluster:7.4.1
    restart: unless-stopped
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - ${REDIS_2_VOLUMES}:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_PORT_NUMBER=6381'
      - 'REDIS_NODES=${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6381'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16381'

  redis-node-3:
    image: bitnamilegacy/redis-cluster:7.4.1
    restart: unless-stopped
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - ${REDIS_3_VOLUMES}:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_PORT_NUMBER=6382'
      - 'REDIS_NODES=${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6382'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16382'

  redis-node-4:
    image: bitnamilegacy/redis-cluster:7.4.1
    restart: unless-stopped
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - ${REDIS_4_VOLUMES}:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_PORT_NUMBER=6383'
      - 'REDIS_NODES=${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6383'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16383'

  redis-node-5:
    image: bitnamilegacy/redis-cluster:7.4.1
    restart: unless-stopped
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - ${REDIS_5_VOLUMES}:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_PORT_NUMBER=6384'
      - 'REDIS_NODES=${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6384'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16384'

  redis-node-6:
    image: bitnamilegacy/redis-cluster:7.4.1
    ports:
      - "6385:6385"
      - "16385:16385"
    volumes:
      - ${REDIS_6_VOLUMES}:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_PORT_NUMBER=6385'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_NODES=${HOST_IP}:6380 ${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6385'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16385'

  redis-insight:
    image: redis/redisinsight:2.64.1
    restart: unless-stopped
    ports:
      - "15540:5540"
    volumes:
      - ${REDIS_INSIGHT_VOLUMES}:/data

  kafka1:
    image: bitnamilegacy/kafka:3.9.0-debian-12-r13
    restart: unless-stopped
    ports:
      - "19094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=2ce827af-446c-456f-9bf9-c2de30f1d3b5
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://localhost:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    volumes:
      - ${KAFKA_1_VOLUMES}:/bitnami/kafka/data

  kafka2:
    image: bitnamilegacy/kafka:3.9.0-debian-12-r13
    restart: unless-stopped
    ports:
      - "19095:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=2ce827af-446c-456f-9bf9-c2de30f1d3b5
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://localhost:19095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    volumes:
      - ${KAFKA_2_VOLUMES}:/bitnami/kafka/data

  kafka3:
    image: bitnamilegacy/kafka:3.9.0-debian-12-r13
    restart: unless-stopped
    ports:
      - "19096:9094"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=2ce827af-446c-456f-9bf9-c2de30f1d3b5
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL://localhost:19096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    volumes:
      - ${KAFKA_3_VOLUMES}:/bitnami/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    ports:
      - '18090:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local-Kafka-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9092,kafka3:9092
    volumes:
      - ${KAFKA_UI_VOLUMES}:/etc/kafkaui
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  nginx:
    image: nginx:1.27.5
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped