version: "3.8"

services:
    mysql:
      image: mysql:8.0.40
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      ports:
        - "13306:3306"
      volumes:
        - ${MYSQL_VOLUMES}:/var/lib/mysql

    redis:
      image: redis:7.4.1
      restart: unless-stopped
      ports:
        - "16379:6379"
      volumes:
        - ${REDIS_VOLUMES}:/data

    redis-insight:
      image: redis/redisinsight:2.64.1
      restart: unless-stopped
      ports:
        - "15540:5540"
      volumes:
        - ${REDIS_INSIGHT_VOLUMES}:/data